# Generated by Django 4.2.6 on 2023-12-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('started', 'Запущена'), ('created', 'Создана'), ('done', 'Завершена'), ('blocked', 'Заблокирована')], default='created', max_length=20, verbose_name='статус рассылки'),
        ),
    ]
