# Generated by Django 4.2.6 on 2023-12-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_time',
            field=models.DateField(help_text='Пожалуйста, используйте следующий формат: <em>YYYY-MM-DD</em>.', verbose_name='конец рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateField(help_text='Пожалуйста, используйте следующий формат: <em>YYYY-MM-DD</em>.', verbose_name='старт рассылки'),
        ),
    ]
