# Generated by Django 4.2.6 on 2023-12-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailing_end_time_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='time_mailing',
            field=models.TimeField(default='12:00', help_text='Пожалуйста, используйте следующий формат: <em>HH:MM</em>.', verbose_name='время рассылки'),
            preserve_default=False,
        ),
    ]
