# Generated by Django 4.2.6 on 2023-12-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
